class RoyalScriptParser:
    CFG = {
        '<program>': [['crown' '~', '<global_dec>', '<user-defined_func>', 'castle', 'treasures', 'identifier', '(', ')', '{', '<body>', 'return', '0', '~', '}', 'reign', '~']],
        '<global_dec>': [['<var_dec>', '<global_dec>'], ['ε']],
        '<var_dec>': [['<dynasty>', '<data_type>', 'identifier', '<vardec_def>']],
        '<dynasty>': [['dynasty'], ['ε']],
        '<vardec_def>': [['<initialization>', '<vardec_more>', '~'], ['[', '<array_size>', ']', '<column>', '<array_initialization>', '<array_more>', '~']],
        '<initialization>': [['=', '<val>'], ['ε']],
        '<vardec_more>': [['ε'], [',', 'identifier', '<initialization>', '<vardec_more>']],
        '<column>': [['[<array_size>]'], ['ε']],
        '<array_initialization>': [['=', '<array_list>'], ['ε']],
        '<array_list>': [['{', '<array_content>', '}']],
        '<array_content>': [['<array_lit>', '<lit_more>'], ['{', '<array_row>', '}', '<row_more>'], ['identifier', '<row_more>']],
        '<array_row>': [['<array_lit>', '<lit_more>']],
        '<row_more>': [['ε'], [',', '<row_more_ext>']],
        '<row_more_ext>': [['{<array_row>}', '<row_more>'], ['identifier', '<row_more>']],
        '<lit_more>': [['ε'], [',', '<array_lit>', '<lit_more>']],
        '<array_more>': [['ε'], [',', 'identifier', '[', '<array_size>',']', '<column>', '<array_initialization>', '<array_more>']],
        '<array_lit>': [['<lit4>'], ['identifier']],
        '<assignment_operator>': [['+='], ['-='], ['*='], ['/='], ['%=']],
        '<assignment_operand>': [['identifier', '<id_ext>', '<more_arith>'], ['<lit3>', '<more_arith>'], ['<arithmetic_operand_2>', '<arithmetic_operator><arithmetic_operand><more_arith>']],
        '<logical_expression>': [['<relational_expression>', '<logical_expression_tail>']],
        '<logical_expression_tail>': [['<logical_operator>', '<logical_operator1>', '<relational_expression>', '<logical_expression_tail>'], ['ε']],
        '<relational_expression>': [['<arithmetic_expression>', '<relational_expression_tail>']],
        '<relational_expression_tail>': [['<relational_operator>', '<arithmetic_expression>', '<relational_expression_tail>'], ['ε']],
        '<arithmetic_expression>': [['<term>', '<arithmetic_expression_tail>']],
        '<arithmetic_expression_tail>': [['+', '<term>', '<arithmetic_expression_tail>'], ['-', '<term>', '<arithmetic_expression_tail>'], ['ε']],
        '<term>': [['<factor>', '<term_tail>']],
        '<term_tail>': [['*', '<factor>', '<term_tail>'], ['/', '<factor>', '<term_tail>'], ['%', '<factor>', '<term_tail>'], ['ε']],
        '<factor>': [['identifier', '<id_ext>'], ['<lit3>'], ['<treasures_mirror>'], ['mirror_lit'], ['scroll_lit'], ['rose_lit'], ['(', '<logical_expression>', ')'], ['<unary_operator>', '<factor>']],
        '<logical_operand>': [['identifier', '<id_ext>', '<logical_operand_ext>'], ['<lit3>', '<more_arith>', '<relational_operator>', '<relational_operand><relational_more>'], ['scroll_lit', '<relational_operator>', '<relational_operand><relational_more>'], ['rose_lit', '<relational_operator>', '<relational_operand>', '<relational_more>'], ['mirror_lit', '<relational_more>'], ['<treasures_mirror>', '<relational_more>'], ['(', '<expression>']],
        '<expression>': [['<logical_expression>', ')']],
        '<expression_2>': [['<arithmetic_expression>', ')'], ['<relational_expression>', ')']],
        '<logical_operand_ext>': [['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'], ['ε']],
        '<logical_operator>': [['&&'], ['||']],
        '<logical_operator1>': [['!'], ['ε']],
        '<more_arith>': [['ε'], ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith>']],
        '<more_log>': [['ε'], ['<logical_operator>', '<logical_operator1>', '<logical_operand>', '<more_log>']],
        '<treasures_mirror>': [['1'], ['0']],
        '<arithmetic_operand_1>': [['identifier', '<id_ext>'], ['<lit3>']],
        '<arithmetic_operand_2>': [['(', '<arithmetic_expression>', ')']],
        '<arithmetic_operand>': [['<arithmetic_operand_1>'], ['<arithmetic_operand_2>']],
        '<arithmetic_operator>': [['+'], ['-'], ['/'], ['*'], ['%']],
        '<relational_operand>': [['identifier', '<id_ext>', '<more_arith>'], ['<lit3>', '<more_arith>'], ['scroll_lit'], ['rose_lit'], ['mirror_lit'], ['treasures_mirror'], ['(', '<expression_2>']],
        '<relational_operator>': [['<'], ['>'], ['<='], ['>='], ['=='], ['!=']],
        '<relational_more>': [['ε'], ['<relational_operator>', '<relational_operand>', '<relational_more>']],
        '<unary>': [['identifier', '<unary_operator>']],
        '<unary_operator>': [['++'], ['--']],
        '<string_operand>': [['<lit1>'], ['identifier', '<id_ext>'], ['toscroll', '(', '<conver_value>', ')']],
        '<string_more>': [['ε'], ['+', '<string_operand>', '<string_more>']],
        '<user-defined_func>': [['spell', '<return_type>', 'identifier', '(', '<param>', ')', '{', '<body>', '<ret_statement>', '}', '<user-defined_func>'], ['ε']],
        '<return_type>': [['<data_type>'], ['chamber']],
        '<param>': [['<data_type>', 'identifier', '<param_more>'], ['ε']],
        '<param_more>': [[',', '<data_type>', 'identifier', '<param_more>'], ['ε']],
        '<body_1>': [['<var_dec>', '<body>'], ['<output>', '<body>'], ['identifier', '<body_1_ext>', '<body>'], ['<user-defined_func>', '<body>'], ['<for_loop>', '<body>']], 
        '<body_1_ext>': [['(', '<args>', ')', '~'], ['<index>', '=', '<val>', '~'], ['<unary_operator>', '~'], ['<index>', '<assignment_operator>', '<assignment_operand>', '~']],        
        '<body_2>': [['<condi_statement>', '<body>']],
        '<body>': [['<body_1>'], ['<body_2>'], ['ε']],
        '<ret_statement>': [['return', '<val1>', '~'], ['ε']],
        '<condi_statement>': [['<if>'], ['<while>'], ['<do_while>']],
        '<for_loop>': [['tale', '(', '<loop_var>', '~', '<relational_expression>', '~', '<unary>', ')', '{', '<loop_body>', '}']],
        '<loop_var>': [['treasures', 'identifier', '=', '<loop_val>'], ['identifier', '<loop_init>']],
        '<loop_init>': [['=', '<loop_val>'], ['ε']],
        '<loop_val>': [['identifier'], ['treasures_lit']],
        '<loop_body>': [['<body_1>', '<loop_body>'], ['<if_break>', '<loop_body>'], ['<while>', '<loop_body>'], ['<do_while>', '<loop_body>'], ['ε']],
        '<if_break>': [['cast', '(', '<condition>', ')', '{', '<body>', '<flow_control>', '}', '<if_break_tail>']],
        '<if_break_tail>': [['<elif_break>'], ['<else_break>'], ['ε']],
        '<elif_break>': [['twist', '(', '<condition>', ')', '{', '<body>', '<flow_control>', '}', '<if_break_tail>']],
        '<else_break>': [['curse', '{', '<body>', '<flow_control>', '}']],
        '<flow_control>': [['break', '~'], ['continue', '~'], ['ε']],
        '<do_while>': [['believe', '{', '<loop_body>', '}', 'forever', '(', '<condition>', ')', '~']],
        '<condition>': [['<logical_expression>'], ['(', '<logical_expression>', ')'], ['<treasures_mirror>', '<more_log>'], ['identifier', '<condi_id_ext>'], ['<logical_operator1>', '<logical_operand>', '<more_log>'], ['mirror_lit', '<relational_more>', '<more_log>'], ['<lit3>', '<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'], ['scroll_lit', '<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'], ['rose_lit', '<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>']],
        '<condi_id_ext>': [['<mirror_init>'], ['<id_ext>', '<other_id_ext>'], ['ε']],
        '<other_id_ext>': [['<other_id_ext_1>', '<other_id_ext_2>']],
        '<other_id_ext_1>': [['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'], ['ε']],
        '<other_id_ext_2>': [['<logical_operator>', '<more_log>'], ['ε']],
        '<mirror_init>': [['==', 'mirror_lit'], ['!=', 'mirror_lit'], ['ε']],
        '<while>': [['forever', '(', '<condition>', ')', '{', '<loop_body>', '}']],
        '<if>': [['cast', '(', '<condition>', ')', '{', '<body>', '}', '<if_tail>']],
        '<if_tail>': [['<elif>'], ['<else>'], ['ε']],
        '<elif>': [['twist', '(', '<condition>', ')', '{', '<body>', '}', '<if_tail>']],
        '<else>': [['curse', '{', '<body>', '}']],
        '<output>': [['granted', '(', '<granted_content>', '<more_granted>', ')', '~']],
        '<granted_content>': [['<granted_content_1>'], ['<granted_content_2>']],
        '<granted_content_1>': [['set_precision'], ['identifier', '<granted_id_ext>']],
        '<granted_content_2>': [['phantom'], ['lengthof', '(', 'identifier', '<index>', ')'], ['<conversion_func>', '(', '<conversion_value>', ')'], ['toscroll', '(', '<conversion_value>', ')', '<string_more>'], ['<treasures_mirror>', '<more_log>'], ['mirror_lit', '<relational_more>', '<more_log>'], ['scroll_lit', '<granted_scroll_ext>'], ['rose_lit', '<granted_rose_ext>'], ['<lit3>', '<granted_lit3_ext>'], ['(', '<granted_open_paren_ext>'], ['<logical_operator1>', '<logical_operand>', '<more_log>']],
        '<granted_open_paren_ext>': [['<arithmetic_expression>', ')', '<more_arith>'], ['<logical_expression>', ')', '<more_log>'], ['<expression_2>', '<relational_more>']],     
        '<granted_id_ext>': [['<unary_operator>'], ['<id_ext>', '<granted_other_id_ext>'], ['ε']],
        '<granted_other_id_ext>': [['+', '<string_operand>', '<string_more>'], ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith>'], ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'], ['<logical_operand_ext>', '<logical_operator>', '<more_log>'], ['ε']],
        '<granted_scroll_ext>': [['+', '<string_operand>', '<string_more>'], ['<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'], ['ε']],    
        '<granted_rose_ext>': [['+', '<string_operand>', '<string_more>'], ['<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'], ['ε']],      
        '<granted_lit3_ext>': [['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith>'], ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'], ['ε']],
        '<more_granted>': [[',', '<granted_content>', '<more_granted>'], ['ε']],
        '<data_type>': [['scroll'], ['treasures'], ['mirror'], ['ocean'], ['rose']],
        '<val>': [['<granted_content_2>'], ['identifier', '<granted_id_ext>'], ['<input>']],
        '<val1>': [['<granted_content_2>'], ['identifier', '<val1_ext>']],
        '<val1_ext>': [['<id_ext>', '<val1_id_ext>'], ['<unary_operator>'], ['ε']],
        '<val1_id_ext>': [['<granted_other_id_ext>'], ['<assignment_operator>', '<assignment_operand>'], ['ε']],
        '<conversion_func>': [['torose'], ['totreasures'], ['toocean'], ['tomirror']],
        '<conversion_value>': [['<lit4>'], ['identifier', '<id_ext>']],
        '<index>': [['[', '<array_size>', ']', '<column1>'], ['ε']],
        '<column1>': [['[', '<array_size>', ']'], ['ε']],
        '<input>': [['wish', '(', 'scroll_lit', ')']],
        '<lit1>': [['scroll_lit'], ['rose_lit']],
        '<lit2>': [['mirror_lit']],
        '<lit3>': [['ocean_lit'], ['treasures_lit']],
        '<lit4>': [['<lit1>'], ['<lit2>'], ['<lit3>']],
        '<func_call>': [['(', '<args>', ')']],
        '<args>': [['<args_val>', '<args_more>'], ['ε']],
        '<args_val>': [['identifier', '<id_ext>'], ['<lit4>']],
        '<args_more>': [[',', '<args_val>', '<args_more>'], ['ε']],
        '<array_element>': [['<index>']],
        '<id_ext>': [['<func_call>'], ['<array_element>'], ['ε']],
        '<array_size>': [['identifier'], ['treasures_lit']],
    }

    PREDICT = {
    # PROGRAM
    ('<program>', 'crown'): ['crown', '~', '<global_dec>', '<user-defined_func>', 'castle', 'treasures', 'identifier', '(', ')', '{', '<body>', 'return', '0', '~', '}', 'reign', '~'],
    # GLOBAL DECLARATION
    ('<global_dec>', 'scroll'): ['<var_dec>', '<global_dec>'],
    ('<global_dec>', 'mirror'): ['<var_dec>', '<global_dec>'],
    ('<global_dec>', 'treasures'): ['<var_dec>', '<global_dec>'],
    ('<global_dec>', 'dynasty'): ['<var_dec>', '<global_dec>'],
    ('<global_dec>', 'rose'): ['<var_dec>', '<global_dec>'],
    ('<global_dec>', 'ocean'): ['<var_dec>', '<global_dec>'],
    ('<global_dec>', 'castle'): ['ε'],
    ('<global_dec>', 'spell'): ['ε'],
    # VARIABLE DECLARATION  
    ('<var_dec>', 'scroll'): ['<dynasty>', '<data_type>', 'identifier', '<vardec_def>'],
    ('<var_dec>', 'mirror'): ['<dynasty>', '<data_type>', 'identifier', '<vardec_def>'],
    ('<var_dec>', 'treasures'): ['<dynasty>', '<data_type>', 'identifier', '<vardec_def>'],
    ('<var_dec>', 'dynasty'): ['<dynasty>', '<data_type>', 'identifier', '<vardec_def>'],
    ('<var_dec>', 'rose'): ['<dynasty>', '<data_type>', 'identifier', '<vardec_def>'],
    ('<var_dec>', 'ocean'): ['<dynasty>', '<data_type>', 'identifier', '<vardec_def>'],
    #CONSTANT
    ('<dynasty>', 'dynasty'): ['dynasty'],
    ('<dynasty>', 'scroll'): ['ε'],
    ('<dynasty>', 'mirror'): ['ε'],
    ('<dynasty>', 'treasures'): ['ε'],
    ('<dynasty>', 'rose'): ['ε'],
    ('<dynasty>', 'ocean'): ['ε'],
    # VARIABLE DEFINITION
    ('<vardec_def>', '~'): ['<initialization>', '<vardec_more>', '~'],
    ('<vardec_def>', '='): ['<initialization>', '<vardec_more>', '~'],
    ('<vardec_def>', ','): ['<initialization>', '<vardec_more>', '~'],
    ('<vardec_def>', '['): ['[', '<array_size>', ']', '<column>', '<array_initialization>', '<array_more>', '~'],
    # VARIABLE INITIALIZATION
    ('<initialization>', '='): ['=', '<val>'],
    ('<initialization>', '~'): ['ε'],
    ('<initialization>', ','): ['ε'],
    # MORE VARIABLE DECLARATION
    ('<vardec_more>', '~'): ['ε'],
    ('<vardec_more>', ','): [',', 'identifier', '<initialization>', '<vardec_more\'>'],
    ('<vardec_more\'>', '~'): ['ε'],
    ('<vardec_more\'>', ','): [',', 'identifier', '<initialization>', '<vardec_more\'>'],
    # COLUMN
    ('<column>', '['): ['[', '<array_size>', ']'],
    ('<column>', '='): ['ε'],
    ('<column>', '~'): ['ε'],
    ('<column>', ','): ['ε'],
    # ARRAY INITIALIZATION
    ('<array_initialization>', '='): ['=', '<array_list>'],
    ('<array_initialization>', '~'): ['ε'],
    ('<array_initialization>', ','): ['ε'],
    # ARRAY LIST
    ('<array_list>', '{'): ['{', '<array_content>', '}'],
    # ARRAY ELEMENT
    ('<array_content>', 'rose_lit'): ['<array_lit>', '<lit_more>'],
    ('<array_content>', 'ocean_lit'): ['<array_lit>', '<lit_more>'],
    ('<array_content>', 'treasures_lit'): ['<array_lit>', '<lit_more>'],
    ('<array_content>', 'scroll_lit'): ['<array_lit>', '<lit_more>'],
    ('<array_content>', 'identifier'): [['<array_lit>', '<lit_more>'], ['identifier', '<row_more>']],
    ('<array_content>', 'mirror_lit'): ['<array_lit>', '<lit_more>'],
    ('<array_content>', '{'): ['{', '<array_row>', '}', '<row_more>'],
    # ARRAY ROW
    ('<array_row>', 'rose_lit'): ['<array_lit>', '<lit_more>'],
    ('<array_row>', 'ocean_lit'): ['<array_lit>', '<lit_more>'],
    ('<array_row>', 'treasures_lit'): ['<array_lit>', '<lit_more>'],
    ('<array_row>', 'scroll_lit'): ['<array_lit>', '<lit_more>'],
    ('<array_row>', 'identifier'): ['<array_lit>', '<lit_more>'],
    ('<array_row>', 'mirror_lit'): ['<array_lit>', '<lit_more>'],
    # ROW MORE
    ('<row_more>', '}'): ['ε'],
    ('<row_more>', ','): [',', '<row_more_ext>'],
    # ROW MORE EXTENSION
    ('<row_more_ext>', '{'): ['{', '<array_row>', '}', '<row_more\'>'],
    ('<row_more_ext>', 'identifier'): ['identifier', '<row_more\'>'],
    ('<row_more\'>', '}'): ['ε'],
    ('<row_more\'>', ','): [',', '<row_more_ext>'],
    # MORE CONTENT
    ('<lit_more>', '}'): ['ε'],
    ('<lit_more>', ','): [',', '<array_lit>', '<lit_more\'>'],
    ('<lit_more\'>', '}'): ['ε'],
    ('<lit_more\'>', ','): [',', '<array_lit>', '<lit_more\'>'],
    # MORE ARRAY DECLARATION
    ('<array_more>', '~'): ['ε'],
    ('<array_more>', ','): [',', 'identifier', '[', '<array_size>', ']', '<column>', '<array_initialization>', '<array_more\'>'],
    ('<array_more\'>', '~'): ['ε'],
    ('<array_more\'>', ','): [',', 'identifier', '[', '<array_size>', ']', '<column>', '<array_initialization>', '<array_more\'>'],
    # ARRAY LITERALS
    ('<array_lit>', 'rose_lit'): ['<lit4>'],
    ('<array_lit>', 'ocean_lit'): ['<lit4>'],
    ('<array_lit>', 'treasures_lit'): ['<lit4>'],
    ('<array_lit>', 'scroll_lit'): ['<lit4>'],
    ('<array_lit>', 'mirror_lit'): ['<lit4>'],
    ('<array_lit>', 'identifier'): ['identifier'],
    # ASSIGNMENT OPERATOR
    ('<assignment_operator>', '+='): ['+='],
    ('<assignment_operator>', '-='): ['-='],
    ('<assignment_operator>', '*='): ['*='],
    ('<assignment_operator>', '/='): ['/='],
    ('<assignment_operator>', '%='): ['%='],
    # ASSIGNMENT OPERAND
    ('<assignment_operand>', 'identifier'): ['identifier', '<id_ext>', '<more_arith>'],
    ('<assignment_operand>', 'ocean_lit'): ['<lit3>', '<more_arith>'],
    ('<assignment_operand>', 'treasures_lit'): ['<lit3>', '<more_arith>'],
    ('<assignment_operand>', '('): ['<arithmetic_operand_2>', '<arithmetic_operator>', '<arithmetic_operand>', '<more_arith>'],
    # LOGICAL EXPRESSION
    ('<logical_expression>', 'rose_lit'): ['<relational_expression>', '<logical_expression_tail>'],
    ('<logical_expression>', '('): ['<relational_expression>', '<logical_expression_tail>'],
    ('<logical_expression>', 'treasures_lit'): ['<relational_expression>', '<logical_expression_tail>'],
    ('<logical_expression>', '0'): ['<relational_expression>', '<logical_expression_tail>'],
    ('<logical_expression>', 'identifier'): ['<relational_expression>', '<logical_expression_tail>'],
    ('<logical_expression>', 'mirror_lit'): ['<relational_expression>', '<logical_expression_tail>'],
    ('<logical_expression>', '++'): ['<relational_expression>', '<logical_expression_tail>'],
    ('<logical_expression>', 'ocean_lit'): ['<relational_expression>', '<logical_expression_tail>'],
    ('<logical_expression>', 'scroll_lit'): ['<relational_expression>', '<logical_expression_tail>'],
    ('<logical_expression>', '--'): ['<relational_expression>', '<logical_expression_tail>'],
    ('<logical_expression>', '1'): ['<relational_expression>', '<logical_expression_tail>'],
    ('<logical_expression_tail>', '&&'): ['<logical_operator>', '<logical_operator1>', '<relational_expression>', '<logical_expression_tail>'],
    ('<logical_expression_tail>', '||'): ['<logical_operator>', '<logical_operator1>', '<relational_expression>', '<logical_expression_tail>'],
    ('<logical_expression_tail>', ')'): ['ε'],
    ('<relational_expression>', 'rose_lit'): ['<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression>', '('): ['<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression>', 'treasures_lit'): ['<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression>', '0'): ['<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression>', 'identifier'): ['<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression>', 'mirror_lit'): ['<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression>', '++'): ['<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression>', 'ocean_lit'): ['<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression>', 'scroll_lit'): ['<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression>', '--'): ['<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression>', '1'): ['<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression_tail>', '>='): ['<relational_operator>', '<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression_tail>', '>'): ['<relational_operator>', '<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression_tail>', '=='): ['<relational_operator>', '<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression_tail>', '!='): ['<relational_operator>', '<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression_tail>', '<='): ['<relational_operator>', '<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression_tail>', '<'): ['<relational_operator>', '<arithmetic_expression>', '<relational_expression_tail>'],
    ('<relational_expression_tail>', '||'): ['ε'],
    ('<relational_expression_tail>', '~'): ['ε'],
    ('<relational_expression_tail>', '&&'): ['ε'],
    ('<relational_expression_tail>', ')'): ['ε'],
    ('<arithmetic_expression>', 'rose_lit'): ['<term>', '<arithmetic_expression_tail>'],
    ('<arithmetic_expression>', '('): ['<term>', '<arithmetic_expression_tail>'],
    ('<arithmetic_expression>', 'treasures_lit'): ['<term>', '<arithmetic_expression_tail>'],
    ('<arithmetic_expression>', '0'): ['<term>', '<arithmetic_expression_tail>'],
    ('<arithmetic_expression>', 'identifier'): ['<term>', '<arithmetic_expression_tail>'],
    ('<arithmetic_expression>', 'mirror_lit'): ['<term>', '<arithmetic_expression_tail>'],
    ('<arithmetic_expression>', '++'): ['<term>', '<arithmetic_expression_tail>'],
    ('<arithmetic_expression>', 'ocean_lit'): ['<term>', '<arithmetic_expression_tail>'],
    ('<arithmetic_expression>', 'scroll_lit'): ['<term>', '<arithmetic_expression_tail>'],
    ('<arithmetic_expression>', '--'): ['<term>', '<arithmetic_expression_tail>'],
    ('<arithmetic_expression>', '1'): ['<term>', '<arithmetic_expression_tail>'],
    ('<arithmetic_expression_tail>', '+'): ['+', '<term>', '<arithmetic_expression_tail>'],
    ('<arithmetic_expression_tail>', '-'): ['-', '<term>', '<arithmetic_expression_tail>'],
    ('<arithmetic_expression_tail>', '<='): ['ε'],
    ('<arithmetic_expression_tail>', '&&'): ['ε'],
    ('<arithmetic_expression_tail>', '>='): ['ε'],
    ('<arithmetic_expression_tail>', '>'): ['ε'],
    ('<arithmetic_expression_tail>', '=='): ['ε'],
    ('<arithmetic_expression_tail>', '!='): ['ε'],
    ('<arithmetic_expression_tail>', '||'): ['ε'],
    ('<arithmetic_expression_tail>', ')'): ['ε'],
    ('<arithmetic_expression_tail>', '~'): ['ε'],
    ('<arithmetic_expression_tail>', '<'): ['ε'],
    ('<term>', 'rose_lit'): ['<factor>', '<term_tail>'],
    ('<term>', '('): ['<factor>', '<term_tail>'],
    ('<term>', 'treasures_lit'): ['<factor>', '<term_tail>'],
    ('<term>', '0'): ['<factor>', '<term_tail>'],
    ('<term>', 'identifier'): ['<factor>', '<term_tail>'],
    ('<term>', 'mirror_lit'): ['<factor>', '<term_tail>'],
    ('<term>', '++'): ['<factor>', '<term_tail>'],
    ('<term>', 'ocean_lit'): ['<factor>', '<term_tail>'],
    ('<term>', 'scroll_lit'): ['<factor>', '<term_tail>'],
    ('<term>', '--'): ['<factor>', '<term_tail>'],
    ('<term>', '1'): ['<factor>', '<term_tail>'],
    ('<term_tail>', '*'): ['*', '<factor>', '<term_tail>'],
    ('<term_tail>', '/'): ['/', '<factor>', '<term_tail>'],
    ('<term_tail>', '%'): ['%', '<factor>', '<term_tail>'],
    ('<term_tail>', '-'): ['ε'],
    ('<term_tail>', ')'): ['ε'],
    ('<term_tail>', '<='): ['ε'],
    ('<term_tail>', '&&'): ['ε'],
    ('<term_tail>', '<'): ['ε'],
    ('<term_tail>', '>'): ['ε'],
    ('<term_tail>', '=='): ['ε'],
    ('<term_tail>', '!='): ['ε'],
    ('<term_tail>', '||'): ['ε'],
    ('<term_tail>', '>='): ['ε'],
    ('<term_tail>', '~'): ['ε'],
    ('<term_tail>', '+'): ['ε'],
    ('<factor>', 'identifier'): ['identifier', '<id_ext>'],
    ('<factor>', 'ocean_lit'): ['<lit3>'],
    ('<factor>', 'treasures_lit'): ['<lit3>'],
    ('<factor>', '1'): ['<treasures_mirror>'],
    ('<factor>', '0'): ['<treasures_mirror>'],
    ('<factor>', 'mirror_lit'): ['mirror_lit'],
    ('<factor>', 'scroll_lit'): ['scroll_lit'],
    ('<factor>', 'rose_lit'): ['rose_lit'],
    ('<factor>', '('): ['(', '<logical_expression>', ')'],
    ('<factor>', '++'): ['<unary_operator>', '<factor>'],
    ('<factor>', '--'): ['<unary_operator>', '<factor>'],
    ('<logical_operand>', 'identifier'): ['identifier', '<id_ext>', '<logical_operand_ext>'],
    ('<logical_operand>', 'ocean_lit'): ['<lit3>', '<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand>', 'treasures_lit'): ['<lit3>', '<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand>', 'scroll_lit'): ['scroll_lit', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand>', 'rose_lit'): ['rose_lit', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand>', 'mirror_lit'): ['mirror_lit', '<relational_more>'],
    ('<logical_operand>', '1'): ['<treasures_mirror>', '<relational_more>'],
    ('<logical_operand>', '0'): ['<treasures_mirror>', '<relational_more>'],
    ('<logical_operand>', '('): ['(', '<expression>'],
    ('<expression>', 'rose_lit'): ['<logical_expression>', ')'],
    ('<expression>', '('): ['<logical_expression>', ')'],
    ('<expression>', 'treasures_lit'): ['<logical_expression>', ')'],
    ('<expression>', '0'): ['<logical_expression>', ')'],
    ('<expression>', 'identifier'): ['<logical_expression>', ')'],
    ('<expression>', 'mirror_lit'): ['<logical_expression>', ')'],
    ('<expression>', '++'): ['<logical_expression>', ')'],
    ('<expression>', 'ocean_lit'): ['<logical_expression>', ')'],
    ('<expression>', 'scroll_lit'): ['<logical_expression>', ')'],
    ('<expression>', '--'): ['<logical_expression>', ')'],
    ('<expression>', '1'): ['<logical_expression>', ')'],
    ('<expression_2>', 'rose_lit'): ['<arithmetic_expression>', ')'],
    ('<expression_2>', '('): ['<arithmetic_expression>', ')'],
    ('<expression_2>', 'treasures_lit'): ['<arithmetic_expression>', ')'],
    ('<expression_2>', '0'): ['<arithmetic_expression>', ')'],
    ('<expression_2>', 'identifier'): ['<arithmetic_expression>', ')'],
    ('<expression_2>', 'mirror_lit'): ['<arithmetic_expression>', ')'],
    ('<expression_2>', '++'): ['<arithmetic_expression>', ')'],
    ('<expression_2>', 'ocean_lit'): ['<arithmetic_expression>', ')'],
    ('<expression_2>', 'scroll_lit'): ['<arithmetic_expression>', ')'],
    ('<expression_2>', '--'): ['<arithmetic_expression>', ')'],
    ('<expression_2>', '1'): ['<arithmetic_expression>', ')'],
    ('<expression_2>', 'rose_lit'): ['<relational_expression>', ')'],
    ('<expression_2>', '('): ['<relational_expression>', ')'],
    ('<expression_2>', 'treasures_lit'): ['<relational_expression>', ')'],
    ('<expression_2>', '0'): ['<relational_expression>', ')'],
    ('<expression_2>', 'identifier'): ['<relational_expression>', ')'],
    ('<expression_2>', 'mirror_lit'): ['<relational_expression>', ')'],
    ('<expression_2>', '++'): ['<relational_expression>', ')'],
    ('<expression_2>', 'ocean_lit'): ['<relational_expression>', ')'],
    ('<expression_2>', 'scroll_lit'): ['<relational_expression>', ')'],
    ('<expression_2>', '--'): ['<relational_expression>', ')'],
    ('<expression_2>', '1'): ['<relational_expression>', ')'],
    ('<logical_operand_ext>', '-'): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand_ext>', '/'): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand_ext>', '*'): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand_ext>', '+'): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand_ext>', '<'): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand_ext>', '>='): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand_ext>', '>'): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand_ext>', '=='): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand_ext>', '!='): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand_ext>', '<='): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand_ext>', '%'): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<logical_operand_ext>', ')'): ['ε'],
    ('<logical_operand_ext>', '~'): ['ε'],
    ('<logical_operand_ext>', '&&'): ['ε'],
    ('<logical_operand_ext>', ','): ['ε'],
    ('<logical_operand_ext>', '||'): ['ε'],
    ('<logical_operator>', '&&'): ['&&'],
    ('<logical_operator>', '||'): ['||'],
    ('<logical_operator1>', '!'): ['!'],
    ('<logical_operator1>', '('): ['ε'],
    ('<logical_operator1>', 'rose_lit'): ['ε'],
    ('<logical_operator1>', 'treasures_lit'): ['ε'],
    ('<logical_operator1>', '0'): ['ε'],
    ('<logical_operator1>', 'identifier'): ['ε'],
    ('<logical_operator1>', 'mirror_lit'): ['ε'],
    ('<logical_operator1>', '++'): ['ε'],
    ('<logical_operator1>', 'ocean_lit'): ['ε'],
    ('<logical_operator1>', 'scroll_lit'): ['ε'],
    ('<logical_operator1>', '--'): ['ε'],
    ('<logical_operator1>', '1'): ['ε'],
    ('<more_arith>', ','): ['ε'], 
    ('<more_arith>', '<='): ['ε'],
    ('<more_arith>', '&&'): ['ε'],
    ('<more_arith>', '>='): ['ε'],
    ('<more_arith>', '>'): ['ε'],
    ('<more_arith>', '=='): ['ε'],
    ('<more_arith>', '!='): ['ε'],
    ('<more_arith>', '~'): ['ε'],
    ('<more_arith>', ')'): ['ε'],
    ('<more_arith>', '||'): ['ε'],
    ('<more_arith>', '<'): ['ε'],
    ('<more_arith>', '-'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith\'>'],
    ('<more_arith>', '/'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith\'>'],
    ('<more_arith>', '*'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith\'>'],
    ('<more_arith>', '+'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith\'>'],
    ('<more_arith>', '%'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith\'>'],
    ('<more_arith\'>', ','): ['ε'],
    ('<more_arith\'>', '<='): ['ε'],
    ('<more_arith\'>', '&&'): ['ε'],
    ('<more_arith\'>', '>='): ['ε'],
    ('<more_arith\'>', '>'): ['ε'],
    ('<more_arith\'>', '=='): ['ε'],
    ('<more_arith\'>', '!='): ['ε'],
    ('<more_arith\'>', '~'): ['ε'],
    ('<more_arith\'>', ')'): ['ε'],
    ('<more_arith\'>', '||'): ['ε'],
    ('<more_arith\'>', '<'): ['ε'],
    ('<more_arith\'>', '-'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith\'>'],
    ('<more_arith\'>', '/'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith\'>'],
    ('<more_arith\'>', '*'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith\'>'],
    ('<more_arith\'>', '+'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith\'>'],
    ('<more_arith\'>', '%'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith\'>'],
    ('<more_log>', ')'): ['ε'],
    ('<more_log>', '~'): ['ε'],
    ('<more_log>', '||'): ['<logical_operator>', '<logical_operator1>', '<logical_operand>', '<more_log\'>'],
    ('<more_log>', '&&'): ['<logical_operator>', '<logical_operator1>', '<logical_operand>', '<more_log\'>'],
    ('<more_log>', ','): ['ε'],
    ('<more_log\'>', ')'): ['ε'],
    ('<more_log\'>', '~'): ['ε'],
    ('<more_log\'>', '&&'): ['<logical_operator>', '<logical_operator1>', '<logical_operand>', '<more_log\'>'],
    ('<more_log\'>', ','): ['ε'],
    ('<more_log\'>', '||'): ['<logical_operator>', '<logical_operator1>', '<logical_operand>', '<more_log\'>'],
    ('<treasures_mirror>', '1'): ['1'],
    ('<treasures_mirror>', '0'): ['0'],
    ('<arithmetic_operand_1>', 'identifier'): ['identifier', '<id_ext>'],
    ('<arithmetic_operand_1>', 'ocean_lit'): ['<lit3>'],
    ('<arithmetic_operand_1>', 'treasures_lit'): ['<lit3>'],
    ('<arithmetic_operand_2>', '('): ['(', '<arithmetic_expression>', ')'],
    ('<arithmetic_operand>', 'ocean_lit'): ['<arithmetic_operand_1>'],
    ('<arithmetic_operand>', 'identifier'): ['<arithmetic_operand_1>'],
    ('<arithmetic_operand>', 'treasures_lit'): ['<arithmetic_operand_1>'],
    ('<arithmetic_operand>', '('): ['<arithmetic_operand_2>'],
    ('<arithmetic_operator>', '+'): ['+'],
    ('<arithmetic_operator>', '-'): ['-'],
    ('<arithmetic_operator>', '/'): ['/'],
    ('<arithmetic_operator>', '*'): ['*'],
    ('<arithmetic_operator>', '%'): ['%'],
    ('<relational_operand>', 'identifier'): ['identifier', '<id_ext>', '<more_arith>'],
    ('<relational_operand>', 'ocean_lit'): ['<lit3>', '<more_arith>'],
    ('<relational_operand>', 'treasures_lit'): ['<lit3>', '<more_arith>'],
    ('<relational_operand>', 'scroll_lit'): ['scroll_lit'],
    ('<relational_operand>', 'rose_lit'): ['rose_lit'],
    ('<relational_operand>', 'mirror_lit'): ['mirror_lit'],
    ('<relational_operand>', 'treasures_mirror'): ['treasures_mirror'],
    ('<relational_operand>', '('): ['(', '<expression_2>'],
    ('<relational_operator>', '<'): ['<'],
    ('<relational_operator>', '>'): ['>'],
    ('<relational_operator>', '<='): ['<='],
    ('<relational_operator>', '>='): ['>='],
    ('<relational_operator>', '=='): ['=='],
    ('<relational_operator>', '!='): ['!='],
    ('<relational_more>', ')'): ['ε'],
    ('<relational_more>', '~'): ['ε'],
    ('<relational_more>', '&&'): ['ε'],
    ('<relational_more>', ','): ['ε'],
    ('<relational_more>', '||'): ['ε'],
    ('<relational_more>', '>='): ['<relational_operator>', '<relational_operand>', '<relational_more\'>'],
    ('<relational_more>', '>'): ['<relational_operator>', '<relational_operand>', '<relational_more\'>'],
    ('<relational_more>', '=='): ['<relational_operator>', '<relational_operand>', '<relational_more\'>'],
    ('<relational_more>', '!='): ['<relational_operator>', '<relational_operand>', '<relational_more\'>'],
    ('<relational_more>', '<='): ['<relational_operator>', '<relational_operand>', '<relational_more\'>'],
    ('<relational_more>', '<'): ['<relational_operator>', '<relational_operand>', '<relational_more\'>'],
    ('<relational_more\'>', ')'): ['ε'],
    ('<relational_more\'>', '~'): ['ε'],
    ('<relational_more\'>', ','): ['ε'],
    ('<relational_more\'>', '&&'): ['ε'],
    ('<relational_more\'>', '||'): ['ε'],
    ('<relational_more\'>', '>='): ['<relational_operator>', '<relational_operand>', '<relational_more\'>'],
    ('<relational_more\'>', '>'): ['<relational_operator>', '<relational_operand>', '<relational_more\'>'],
    ('<relational_more\'>', '=='): ['<relational_operator>', '<relational_operand>', '<relational_more\'>'],
    ('<relational_more\'>', '!='): ['<relational_operator>', '<relational_operand>', '<relational_more\'>'],
    ('<relational_more\'>', '<='): ['<relational_operator>', '<relational_operand>', '<relational_more\'>'],
    ('<relational_more\'>', '<'): ['<relational_operator>', '<relational_operand>', '<relational_more\'>'],
    ('<unary>', 'identifier'): ['identifier', '<unary_operator>'],
    ('<unary_operator>', '++'): ['++'],
    ('<unary_operator>', '--'): ['--'],
    ('<string_operand>', 'rose_lit'): ['<lit1>'],
    ('<string_operand>', 'scroll_lit'): ['<lit1>'],
    ('<string_operand>', 'identifier'): ['identifier', '<id_ext>'],
    ('<string_operand>', 'toscroll'): ['toscroll', '(', '<conver_value>', ')'],
    ('<string_more>', '~'): ['ε'],
    ('<string_more>', ','): ['ε'],
    ('<string_more>', ')'): ['ε'],
    ('<string_more>', '+'): ['+', '<string_operand>', '<string_more\'>'],
    ('<string_more\'>', '~'): ['ε'],
    ('<string_more\'>', ','): ['ε'],
    ('<string_more\'>', ')'): ['ε'],
    ('<string_more\'>', '+'): ['+', '<string_operand>', '<string_more\'>'],
    ('<user-defined_func>', 'spell'): ['spell', '<return_type>', 'identifier', '(', '<param>', ')', '{', '<body>', '<ret_statement>', '}', '<user-defined_func>'],
    ('<user-defined_func>', 'scroll'): ['ε'],
    ('<user-defined_func>', 'forever'): ['ε'],
    ('<user-defined_func>', 'mirror'): ['ε'],
    ('<user-defined_func>', 'identifier'): ['ε'],
    ('<user-defined_func>', 'tale'): ['ε'],
    ('<user-defined_func>', 'treasures'): ['ε'],
    ('<user-defined_func>', 'break'): ['ε'],
    ('<user-defined_func>', 'rose'): ['ε'],
    ('<user-defined_func>', 'castle'): ['ε'],
    ('<user-defined_func>', 'granted'): ['ε'],
    ('<user-defined_func>', '}'): ['ε'],
    ('<user-defined_func>', 'cast'): ['ε'],
    ('<user-defined_func>', 'dynasty'): ['ε'],
    ('<user-defined_func>', 'ocean'): ['ε'],
    ('<user-defined_func>', 'continue'): ['ε'],
    ('<user-defined_func>', 'return'): ['ε'],
    ('<user-defined_func>', 'believe'): ['ε'],
    ('<return_type>', 'scroll'): ['<data_type>'],
    ('<return_type>', 'mirror'): ['<data_type>'],
    ('<return_type>', 'treasures'): ['<data_type>'],
    ('<return_type>', 'rose'): ['<data_type>'],
    ('<return_type>', 'ocean'): ['<data_type>'],
    ('<return_type>', 'chamber'): ['chamber'],
    ('<param>', 'scroll'): ['<data_type>', 'identifier', '<param_more>'],
    ('<param>', 'mirror'): ['<data_type>', 'identifier', '<param_more>'],
    ('<param>', 'treasures'): ['<data_type>', 'identifier', '<param_more>'],
    ('<param>', 'rose'): ['<data_type>', 'identifier', '<param_more>'],
    ('<param>', 'ocean'): ['<data_type>', 'identifier', '<param_more>'],
    ('<param>', ')'): ['ε'],
    ('<param_more>', ','): [',', '<data_type>', 'identifier', '<param_more>'],
    ('<param_more>', ')'): ['ε'],
    ('<body_1>', 'scroll'): ['<var_dec>', '<body>'],
    ('<body_1>', 'mirror'): ['<var_dec>', '<body>'],
    ('<body_1>', 'treasures'): ['<var_dec>', '<body>'],
    ('<body_1>', 'dynasty'): ['<var_dec>', '<body>'],
    ('<body_1>', 'rose'): ['<var_dec>', '<body>'],
    ('<body_1>', 'ocean'): ['<var_dec>', '<body>'],
    ('<body_1>', 'granted'): ['<output>', '<body>'],
    ('<body_1>', 'identifier'): ['identifier', '<body_1_ext>', '<body>'],
    ('<body_1>', 'spell'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'forever'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'mirror'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'identifier'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'tale'): ['<for_loop>', '<body>'],
    ('<body_1>', 'spell'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'treasures'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'break'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'rose'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'granted'): ['<user-defined_func>', '<body>'],
    ('<body_1>', '}'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'cast'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'dynasty'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'ocean'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'continue'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'return'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'believe'): ['<user-defined_func>', '<body>'],
    ('<body_1>', 'tale'): ['<for_loop>', '<body>'],
    ('<body_1_ext>', '('): ['(', '<args>', ')', '~'],
    ('<body_1_ext>', '['): ['<index>', '=', '<val>', '~'],
    ('<body_1_ext>', '='): ['<index>', '=', '<val>', '~'],
    ('<body_1_ext>', '++'): ['<unary_operator>', '~'],
    ('<body_1_ext>', '--'): ['<unary_operator>', '~'],
    ('<body_1_ext>', '-='): ['<index>', '<assignment_operator>', '<assignment_operand>', '~'],
    ('<body_1_ext>', '+='): ['<index>', '<assignment_operator>', '<assignment_operand>', '~'],
    ('<body_1_ext>', '['): ['<index>', '<assignment_operator>', '<assignment_operand>', '~'],
    ('<body_1_ext>', '/='): ['<index>', '<assignment_operator>', '<assignment_operand>', '~'],
    ('<body_1_ext>', '*='): ['<index>', '<assignment_operator>', '<assignment_operand>', '~'],
    ('<body_1_ext>', '%='): ['<index>', '<assignment_operator>', '<assignment_operand>', '~'],
    ('<body_2>', 'cast'): ['<condi_statement>', '<body>'],
    ('<body_2>', 'forever'): ['<condi_statement>', '<body>'],
    ('<body_2>', 'believe'): ['<condi_statement>', '<body>'],
    ('<body>', 'scroll'): ['<body_1>'],
    ('<body>', 'forever'): ['<body_1>'],
    ('<body>', 'mirror'): ['<body_1>'],
    ('<body>', 'identifier'): ['<body_1>'],
    ('<body>', 'tale'): ['<body_1>'],
    ('<body>', 'spell'): ['<body_1>'],
    ('<body>', 'treasures'): ['<body_1>'],
    ('<body>', 'break'): ['<body_1>'],
    ('<body>', 'rose'): ['<body_1>'],
    ('<body>', 'granted'): ['<body_1>'],
    ('<body>', '}'): ['ε'],
    ('<body>', 'cast'): ['<body_2>'],
    ('<body>', 'dynasty'): ['<body_1>'],
    ('<body>', 'ocean'): ['<body_1>'],
    ('<body>', 'continue'): ['<body_1>'],
    ('<body>', 'return'): ['<body_1>'],
    ('<body>', 'believe'): ['<body_2>'],
    ('<body>', 'forever'): ['<body_2>'],
    ('<body>', 'cast'): ['<body_2>'],
    ('<ret_statement>', 'return'): ['return', '<val1>', '~'],
    ('<ret_statement>', '}'): ['ε'],
    ('<condi_statement>', 'cast'): ['<if>'],
    ('<condi_statement>', 'forever'): ['<while>'],
    ('<condi_statement>', 'believe'): ['<do_while>'],
    ('<for_loop>', 'tale'): ['tale', '(', '<loop_var>', '~', '<relational_expression>', '~', '<unary>', ')', '{', '<loop_body>', '}'],
    ('<loop_var>', 'treasures'): ['treasures', 'identifier', '=', '<loop_val>'],
    ('<loop_var>', 'identifier'): ['identifier', '<loop_init>'],
    ('<loop_init>', '='): ['=', '<loop_val>'],
    ('<loop_init>', '~'): ['ε'],
    ('<loop_val>', 'identifier'): ['identifier'],
    ('<loop_val>', 'treasures_lit'): ['treasures_lit'],
    ('<loop_body>', 'granted'): ['<body_1>', '<loop_body>'],
    ('<loop_body>', 'scroll'): ['<body_1>', '<loop_body>'],
    ('<loop_body>', 'forever'): ['<body_1>', '<loop_body>'],
    ('<loop_body>', 'mirror'): ['<body_1>', '<loop_body>'],
    ('<loop_body>', '}'): ['ε'],
    ('<loop_body>', 'cast'): ['<if_break>', '<loop_body>'],
    ('<loop_body>', 'dynasty'): ['<body_1>', '<loop_body>'],
    ('<loop_body>', 'identifier'): ['<body_1>', '<loop_body>'],
    ('<loop_body>', 'tale'): ['<body_1>', '<loop_body>'],
    ('<loop_body>', 'spell'): ['<body_1>', '<loop_body>'],
    ('<loop_body>', 'ocean'): ['<body_1>', '<loop_body>'],
    ('<loop_body>', 'treasures'): ['<body_1>', '<loop_body>'],
    ('<loop_body>', 'rose'): ['<body_1>', '<loop_body>'],
    ('<loop_body>', 'believe'): ['<body_1>', '<loop_body>'],
    ('<loop_body>', 'forever'): ['<while>', '<loop_body>'],
    ('<loop_body>', 'believe'): ['<do_while>', '<loop_body>'],
    ('<if_break>', 'cast'): ['cast', '(', '<condition>', ')', '{', '<body>', '<flow_control>', '}', '<if_break_tail>'],
    ('<if_break_tail>', 'twist'): ['<elif_break>'],
    ('<if_break_tail>', 'curse'): ['<else_break>'],
    ('<if_break_tail>', 'granted'): ['ε'],
    ('<if_break_tail>', 'scroll'): ['ε'],
    ('<if_break_tail>', 'forever'): ['ε'],
    ('<if_break_tail>', 'mirror'): ['ε'],
    ('<if_break_tail>', '}'): ['ε'],
    ('<if_break_tail>', 'cast'): ['ε'],
    ('<if_break_tail>', 'dynasty'): ['ε'],
    ('<if_break_tail>', 'identifier'): ['ε'],
    ('<if_break_tail>', 'tale'): ['ε'],
    ('<if_break_tail>', 'spell'): ['ε'],
    ('<if_break_tail>', 'ocean'): ['ε'],
    ('<if_break_tail>', 'treasures'): ['ε'],
    ('<if_break_tail>', 'rose'): ['ε'],
    ('<if_break_tail>', 'believe'): ['ε'],
    ('<elif_break>', 'twist'): ['twist', '(', '<condition>', ')', '{', '<body>', '<flow_control>', '}', '<if_break_tail>'],
    ('<else_break>', 'curse'): ['curse', '{', '<body>', '<flow_control>', '}'],
    ('<flow_control>', 'break'): ['break', '~'],
    ('<flow_control>', 'continue'): ['continue', '~'],
    ('<flow_control>', '}'): ['ε'],
    ('<do_while>', 'believe'): ['believe', '{', '<loop_body>', '}', 'forever', '(', '<condition>', ')', '~'],
    ('<condition>', 'rose_lit'): ['<logical_expression>'],
    ('<condition>', '('): ['<logical_expression>'],
    ('<condition>', 'treasures_lit'): ['<logical_expression>'],
    ('<condition>', '0'): ['<logical_expression>'],
    ('<condition>', 'identifier'): ['<logical_expression>'],
    ('<condition>', 'mirror_lit'): ['<logical_expression>'],
    ('<condition>', '++'): ['<logical_expression>'],
    ('<condition>', 'ocean_lit'): ['<logical_expression>'],
    ('<condition>', 'scroll_lit'): ['<logical_expression>'],
    ('<condition>', '--'): ['<logical_expression>'],
    ('<condition>', '1'): ['<logical_expression>'],
    ('<condition>', '('): ['(', '<logical_expression>', ')'],
    ('<condition>', '0'): ['<treasures_mirror>', '<more_log>'],
    ('<condition>', '1'): ['<treasures_mirror>', '<more_log>'],
    ('<condition>', 'identifier'): ['identifier', '<condi_id_ext>'],
    ('<condition>', '!'): ['<logical_operator1>', '<logical_operand>', '<more_log>'],
    ('<condition>', 'rose_lit'): ['<logical_operator1>', '<logical_operand>', '<more_log>'],
    ('<condition>', '('): ['<logical_operator1>', '<logical_operand>', '<more_log>'],
    ('<condition>', 'treasures_lit'): ['<logical_operator1>', '<logical_operand>', '<more_log>'],
    ('<condition>', '0'): ['<logical_operator1>', '<logical_operand>', '<more_log>'],
    ('<condition>', 'identifier'): ['<logical_operator1>', '<logical_operand>', '<more_log>'],
    ('<condition>', 'mirror_lit'): ['<logical_operator1>', '<logical_operand>', '<more_log>'],
    ('<condition>', 'ocean_lit'): ['<logical_operator1>', '<logical_operand>', '<more_log>'],
    ('<condition>', 'scroll_lit'): ['<logical_operator1>', '<logical_operand>', '<more_log>'],
    ('<condition>', '1'): ['<logical_operator1>', '<logical_operand>', '<more_log>'],
    ('<condition>', 'mirror_lit'): ['mirror_lit', '<relational_more>', '<more_log>'],
    ('<condition>', 'ocean_lit'): ['<lit3>', '<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'],
    ('<condition>', 'treasures_lit'): ['<lit3>', '<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'],
    ('<condition>', 'scroll_lit'): ['scroll_lit', '<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'],
    ('<condition>', 'rose_lit'): ['rose_lit', '<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'],
    ('<condi_id_ext>', '<mirror_init>'): ['==', 'mirror_lit'],
    ('<condi_id_ext>', '<id_ext>'): ['<id_ext>', '<other_id_ext>'],
    ('<condi_id_ext>', 'ε'): [')'],
    
    ('<other_id_ext>', '<other_id_ext_1>'): ['<other_id_ext_1>', '<other_id_ext_2>'],
    
    ('<other_id_ext_1>', '<more_arith>'): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'],
    ('<other_id_ext_1>', 'ε'): ['||', '&&', ')'],
    
    ('<other_id_ext_2>', '<logical_operator>'): ['<logical_operator>', '<more_log>'],
    ('<other_id_ext_2>', 'ε'): [')'],
    
    ('<mirror_init>', '=='): ['==', 'mirror_lit'],
    ('<mirror_init>', '!='): ['!=', 'mirror_lit'],
    ('<mirror_init>', 'ε'): [')'],
    
    ('<while>', 'forever'): ['forever', '(', '<condition>', ')', '{', '<loop_body>', '}'],
    
    ('<if>', 'cast'): ['cast', '(', '<condition>', ')', '{', '<body>', '}', '<if_tail>'],
    
    ('<if_tail>', 'twist'): ['<elif>'],
    ('<if_tail>', 'curse'): ['<else>'],
    ('<if_tail>', 'ε'): ['scroll', 'forever', 'mirror', 'identifier', 'tale', 'spell', 'treasures', 'break', 'rose', 'granted', '}', 'cast', 'dynasty', 'ocean', 'continue', 'return', 'believe'],
    
    ('<elif>', 'twist'): ['twist', '(', '<condition>', ')', '{', '<body>', '}', '<if_tail>'],
    
    ('<else>', 'curse'): ['curse', '{', '<body>', '}'],
    
    ('<output>', 'granted'): ['granted', '(', '<granted_content>', '<more_granted>', ')', '~'],
    
    ('<granted_content>', 'set_precision'): ['<granted_content_1>'],
    ('<granted_content>', 'identifier'): ['<granted_content_1>'],
    ('<granted_content>', 'lengthof'): ['<granted_content_2>'],
    ('<granted_content>', '('): ['<granted_content_2>'],
    ('<granted_content>', 'treasures_lit'): ['<granted_content_2>'],
    ('<granted_content>', 'tomirror'): ['<granted_content_2>'],
    ('<granted_content>', 'torose'): ['<granted_content_2>'],
    ('<granted_content>', '0'): ['<granted_content_2>'],
    ('<granted_content>', 'mirror_lit'): ['<granted_content_2>'],
    ('<granted_content>', 'scroll_lit'): ['<granted_content_2>'],
    ('<granted_content>', '!'): ['<granted_content_2>'],
    ('<granted_content>', 'rose_lit'): ['<granted_content_2>'],
    ('<granted_content>', 'toocean'): ['<granted_content_2>'],
    ('<granted_content>', 'ocean_lit'): ['<granted_content_2>'],
    ('<granted_content>', '1'): ['<granted_content_2>'],
    ('<granted_content>', 'toscroll'): ['<granted_content_2>'],
    ('<granted_content>', 'phantom'): ['<granted_content_2>'],
    ('<granted_content>', 'totreasures'): ['<granted_content_2>'],
    
    ('<granted_content_1>', 'set_precision'): ['set_precision'],
    ('<granted_content_1>', 'identifier'): ['identifier', '<granted_id_ext>'],
    
    ('<granted_content_2>', 'phantom'): ['phantom'],
    ('<granted_content_2>', 'lengthof'): ['lengthof', '(', 'identifier', '<index>', ')'],
    ('<granted_content_2>', 'tomirror'): ['<conversion_func>', '(', '<conversion_value>', ')'],
    ('<granted_content_2>', 'toocean'): ['<conversion_func>', '(', '<conversion_value>', ')'],
    ('<granted_content_2>', 'torose'): ['<conversion_func>', '(', '<conversion_value>', ')'],
    ('<granted_content_2>', 'totreasures'): ['<conversion_func>', '(', '<conversion_value>', ')'],
    ('<granted_content_2>', 'toscroll'): ['toscroll', '(', '<conversion_value>', ')', '<string_more>'],
    ('<granted_content_2>', '1'): ['<treasures_mirror>', '<more_log>'],
    ('<granted_content_2>', '0'): ['<treasures_mirror>', '<more_log>'],
    ('<granted_content_2>', 'mirror_lit'): ['mirror_lit', '<relational_more>', '<more_log>'],
    ('<granted_content_2>', 'scroll_lit'): ['scroll_lit', '<granted_scroll_ext>'],
    ('<granted_content_2>', 'rose_lit'): ['rose_lit', '<granted_rose_ext>'],
    ('<granted_content_2>', 'ocean_lit'): ['<lit3>', '<granted_lit3_ext>'],
    ('<granted_content_2>', 'treasures_lit'): ['<lit3>', '<granted_lit3_ext>'],
    ('<granted_content_2>', '('): ['(', '<granted_open_paren_ext>'],
    ('<granted_content_2>', '!'): ['<logical_operator1>', '<logical_operand>', '<more_log>'],
    
    ('<granted_open_paren_ext>', 'rose_lit'): ['<arithmetic_expression>', ')', '<more_arith>'],
    ('<granted_open_paren_ext>', '('): ['<arithmetic_expression>', ')', '<more_arith>'],
    ('<granted_open_paren_ext>', 'treasures_lit'): ['<arithmetic_expression>', ')', '<more_arith>'],
    ('<granted_open_paren_ext>', '0'): ['<arithmetic_expression>', ')', '<more_arith>'],
    ('<granted_open_paren_ext>', 'identifier'): ['<arithmetic_expression>', ')', '<more_arith>'],
    ('<granted_open_paren_ext>', 'mirror_lit'): ['<arithmetic_expression>', ')', '<more_arith>'],
    ('<granted_open_paren_ext>', '++'): ['<arithmetic_expression>', ')', '<more_arith>'],
    ('<granted_open_paren_ext>', 'ocean_lit'): ['<arithmetic_expression>', ')', '<more_arith>'],
    ('<granted_open_paren_ext>', 'scroll_lit'): ['<arithmetic_expression>', ')', '<more_arith>'],
    ('<granted_open_paren_ext>', '--'): ['<arithmetic_expression>', ')', '<more_arith>'],
    ('<granted_open_paren_ext>', '1'): ['<arithmetic_expression>', ')', '<more_arith>'],
    
    ('<granted_id_ext>', '++'): ['<unary_operator>'],
    ('<granted_id_ext>', '--'): ['<unary_operator>'],
    ('<granted_id_ext>', '<id_ext>'): ['<id_ext>', '<granted_other_id_ext>'],
    ('<granted_id_ext>', 'ε'): ['~', ',', ')'],
    
    ('<granted_other_id_ext>', '+'): ['+', '<string_operand>', '<string_more>'],
    ('<granted_other_id_ext>', '-'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith>'],
    ('<granted_other_id_ext>', '/'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith>'],
    ('<granted_other_id_ext>', '*'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith>'],
    ('<granted_other_id_ext>', '%'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith>'],
    ('<granted_other_id_ext>', '<more_arith>'): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>'],
    ('<granted_other_id_ext>', '<logical_operand_ext>'): ['<logical_operand_ext>', '<logical_operator>', '<more_log>'],
    ('<granted_other_id_ext>', 'ε'): ['~', ',', ')'],
    
    ('<granted_scroll_ext>', '+'): ['+', '<string_operand>', '<string_more>'],
    ('<granted_scroll_ext>', '<relational_operator>'): ['<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'],
    ('<granted_scroll_ext>', 'ε'): ['~', ',', ')'],
    
    ('<granted_rose_ext>', '+'): ['+', '<string_operand>', '<string_more>'],
    ('<granted_rose_ext>', '<relational_operator>'): ['<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'],
    ('<granted_rose_ext>', 'ε'): ['~', ',', ')'],
    
    ('<granted_lit3_ext>', '-'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith>'],
    ('<granted_lit3_ext>', '/'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith>'],
    ('<granted_lit3_ext>', '*'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith>'],
    ('<granted_lit3_ext>', '+'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith>'],
    ('<granted_lit3_ext>', '%'): ['<arithmetic_operator>', '<arithmetic_operand>', '<more_arith>'],
    ('<granted_lit3_ext>', '<more_arith>'): ['<more_arith>', '<relational_operator>', '<relational_operand>', '<relational_more>', '<more_log>'],
    ('<granted_lit3_ext>', 'ε'): ['~', ',', ')'],
    
    ('<more_granted>', ','): [',', '<granted_content>', '<more_granted>'],
    ('<more_granted>', 'ε'): [')'],
    
    ('<data_type>', 'scroll'): ['scroll'],
    ('<data_type>', 'treasures'): ['treasures'],
    ('<data_type>', 'mirror'): ['mirror'],
    ('<data_type>', 'ocean'): ['ocean'],
    ('<data_type>', 'rose'): ['rose'],
     ('<val>', 'lengthof'): ['<granted_content_2>'],
    ('<val>', '('): ['<granted_content_2>'],
    ('<val>', 'treasures_lit'): ['<granted_content_2>'],
    ('<val>', 'tomirror'): ['<granted_content_2>'],
    ('<val>', 'torose'): ['<granted_content_2>'],
    ('<val>', '0'): ['<granted_content_2>'],
    ('<val>', 'mirror_lit'): ['<granted_content_2>'],
    ('<val>', 'identifier'): ['identifier', '<granted_id_ext>'],
    ('<val>', 'scroll_lit'): ['<granted_content_2>'],
    ('<val>', '!'): ['<granted_content_2>'],
    ('<val>', 'rose_lit'): ['<granted_content_2>'],
    ('<val>', 'toocean'): ['<granted_content_2>'],
    ('<val>', 'ocean_lit'): ['<granted_content_2>'],
    ('<val>', '1'): ['<granted_content_2>'],
    ('<val>', 'toscroll'): ['<granted_content_2>'],
    ('<val>', 'phantom'): ['<granted_content_2>'],
    ('<val>', 'totreasures'): ['<granted_content_2>'],
    ('<val>', 'wish'): ['<input>'],
    
    # PREDICT(<val1>) rules
    ('<val1>', 'lengthof'): ['<granted_content_2>'],
    ('<val1>', '('): ['<granted_content_2>'],
    ('<val1>', 'treasures_lit'): ['<granted_content_2>'],
    ('<val1>', 'tomirror'): ['<granted_content_2>'],
    ('<val1>', 'torose'): ['<granted_content_2>'],
    ('<val1>', '0'): ['<granted_content_2>'],
    ('<val1>', 'mirror_lit'): ['<granted_content_2>'],
    ('<val1>', 'identifier'): ['identifier', '<val1_ext>'],
    ('<val1>', 'scroll_lit'): ['<granted_content_2>'],
    ('<val1>', '!'): ['<granted_content_2>'],
    ('<val1>', 'rose_lit'): ['<granted_content_2>'],
    ('<val1>', 'toocean'): ['<granted_content_2>'],
    ('<val1>', 'ocean_lit'): ['<granted_content_2>'],
    ('<val1>', '1'): ['<granted_content_2>'],
    ('<val1>', 'toscroll'): ['<granted_content_2>'],
    ('<val1>', 'phantom'): ['<granted_content_2>'],
    ('<val1>', 'totreasures'): ['<granted_content_2>'],
    
    # PREDICT(<val1_ext>) rules
    ('<val1_ext>', '('): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '>'): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '=='): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '+='): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '!='): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '||'): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '>='): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '<='): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '~'): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '['): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '%='): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '/='): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '+'): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '-'): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '/'): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '*'): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '&&'): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '%'): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '-='): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '*='): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '<'): ['<id_ext>', '<val1_id_ext>'],
    ('<val1_ext>', '++'): ['<unary_operator>'],
    ('<val1_ext>', '--'): ['<unary_operator>'],
    ('<val1_ext>', '~'): ['ε'],
    
    # PREDICT(<val1_id_ext>) rules
    ('<val1_id_ext>', '-'): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '/'): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '*'): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '&&'): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '<='): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '%'): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '<'): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '>'): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '=='): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '!='): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '||'): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '>='): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '~'): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '+'): ['<granted_other_id_ext>'],
    ('<val1_id_ext>', '-='): ['<assignment_operator>', '<assignment_operand>'],
    ('<val1_id_ext>', '+='): ['<assignment_operator>', '<assignment_operand>'],
    ('<val1_id_ext>', '%='): ['<assignment_operator>', '<assignment_operand>'],
    ('<val1_id_ext>', '/='): ['<assignment_operator>', '<assignment_operand>'],
    ('<val1_id_ext>', '*='): ['<assignment_operator>', '<assignment_operand>'],
    ('<val1_id_ext>', '~'): ['ε'],
    
    # PREDICT(<conversion_func>) rules
    ('<conversion_func>', 'torose'): ['torose'],
    ('<conversion_func>', 'totreasures'): ['totreasures'],
    ('<conversion_func>', 'toocean'): ['toocean'],
    ('<conversion_func>', 'tomirror'): ['tomirror'],
    
    # PREDICT(<conversion_value>) rules
    ('<conversion_value>', 'rose_lit'): ['<lit4>'],
    ('<conversion_value>', 'ocean_lit'): ['<lit4>'],
    ('<conversion_value>', 'treasures_lit'): ['<lit4>'],
    ('<conversion_value>', 'scroll_lit'): ['<lit4>'],
    ('<conversion_value>', 'mirror_lit'): ['<lit4>'],
    ('<conversion_value>', 'identifier'): ['identifier', '<id_ext>'],
    
    # PREDICT(<index>) rules
    ('<index>', '['): ['[', '<array_size>', ']', '<column1>'],
    ('<index>', ','): ['ε'],
    ('<index>', '='): ['ε'],
    ('<index>', '>'): ['ε'],
    ('<index>', '=='): ['ε'],
    ('<index>', '+='): ['ε'],
    ('<index>', '~'): ['ε'],
    ('<index>', '||'): ['ε'],
    ('<index>', ')'): ['ε'],
    ('<index>', '>='): ['ε'],
    ('<index>', '!='): ['ε'],
    ('<index>', '<='): ['ε'],
    ('<index>', '%='): ['ε'],
    ('<index>', '/='): ['ε'],
    ('<index>', '+'): ['ε'],
    ('<index>', '-'): ['ε'],
    ('<index>', '/'): ['ε'],
    ('<index>', '*'): ['ε'],
    ('<index>', '&&'): ['ε'],
    ('<index>', '%'): ['ε'],
    ('<index>', '-='): ['ε'],
    ('<index>', '*='): ['ε'],
    ('<index>', '<'): ['ε'],
    
    # PREDICT(<column1>) rules
    ('<column1>', '['): ['[', '<array_size>', ']'],
    ('<column1>', ','): ['ε'],
    ('<column1>', '='): ['ε'],
    ('<column1>', '>'): ['ε'],
    ('<column1>', '=='): ['ε'],
    ('<column1>', '+='): ['ε'],
    ('<column1>', '~'): ['ε'],
    ('<column1>', '||'): ['ε'],
    ('<column1>', ')'): ['ε'],
    ('<column1>', '>='): ['ε'],
    ('<column1>', '!='): ['ε'],
    ('<column1>', '<='): ['ε'],
    ('<column1>', '%='): ['ε'],
    ('<column1>', '/='): ['ε'],
    ('<column1>', '+'): ['ε'],
    ('<column1>', '-'): ['ε'],
    ('<column1>', '/'): ['ε'],
    ('<column1>', '*'): ['ε'],
    ('<column1>', '&&'): ['ε'],
    ('<column1>', '%'): ['ε'],
    ('<column1>', '-='): ['ε'],
    ('<column1>', '*='): ['ε'],
    ('<column1>', '<'): ['ε'],
    
    # PREDICT(<input>) rules
    ('<input>', 'wish'): ['wish', '(', 'scroll_lit', ')'],
    
    # PREDICT(<lit1>) rules
    ('<lit1>', 'scroll_lit'): ['scroll_lit'],
    ('<lit1>', 'rose_lit'): ['rose_lit'],
    
    # PREDICT(<lit2>) rules
    ('<lit2>', 'mirror_lit'): ['mirror_lit'],
    
    # PREDICT(<lit3>) rules
    ('<lit3>', 'ocean_lit'): ['ocean_lit'],
    ('<lit3>', 'treasures_lit'): ['treasures_lit'],
    
    # PREDICT(<lit4>) rules
    ('<lit4>', 'rose_lit'): ['<lit1>'],
    ('<lit4>', 'scroll_lit'): ['<lit1>'],
    ('<lit4>', 'mirror_lit'): ['<lit2>'],
    ('<lit4>', 'ocean_lit'): ['<lit3>'],
    ('<lit4>', 'treasures_lit'): ['<lit3>'],
    
    # PREDICT(<func_call>) rules
    ('<func_call>', '('): ['(', '<args>', ')'],
    
    # PREDICT(<args>) rules
    ('<args>', 'rose_lit'): ['<args_val>', '<args_more>'],
    ('<args>', 'ocean_lit'): ['<args_val>', '<args_more>'],
    ('<args>', 'treasures_lit'): ['<args_val>', '<args_more>'],
    ('<args>', 'scroll_lit'): ['<args_val>', '<args_more>'],
    ('<args>', 'identifier'): ['<args_val>', '<args_more>'],
    ('<args>', 'mirror_lit'): ['<args_val>', '<args_more>'],
    ('<args>', ')'): ['ε'],
    
    # PREDICT(<args_val>) rules
    ('<args_val>', 'identifier'): ['identifier', '<id_ext>'],
    ('<args_val>', 'rose_lit'): ['<lit4>'],
    ('<args_val>', 'ocean_lit'): ['<lit4>'],
    ('<args_val>', 'treasures_lit'): ['<lit4>'],
    ('<args_val>', 'scroll_lit'): ['<lit4>'],
    ('<args_val>', 'mirror_lit'): ['<lit4>'],
    
    # PREDICT(<args_more>) rules
    ('<args_more>', ','): [',', '<args_val>', '<args_more>'],
    ('<args_more>', ')'): ['ε'],
    
    # PREDICT(<array_element>) rules
    ('<array_element>', ','): ['<index>'],
    ('<array_element>', '>'): ['<index>'],
    ('<array_element>', '=='): ['<index>'],
    ('<array_element>', '+='): ['<index>'],
    ('<array_element>', '~'): ['<index>'],
    ('<array_element>', '||'): ['<index>'],
    ('<array_element>', '>='): ['<index>'],
    ('<array_element>', ')'): ['<index>'],
    ('<array_element>', '!='): ['<index>'],
    ('<array_element>', '<='): ['<index>'],
    ('<array_element>', '['): ['<index>'],
    ('<array_element>', '%='): ['<index>'],
    ('<array_element>', '/='): ['<index>'],
    ('<array_element>', '+'): ['<index>'],
    ('<array_element>', '-'): ['<index>'],
    ('<array_element>', '/'): ['<index>'],
    ('<array_element>', '*'): ['<index>'],
    ('<array_element>', '&&'): ['<index>'],
    ('<array_element>', '%'): ['<index>'],
    ('<array_element>', '-='): ['<index>'],
    ('<array_element>', '*='): ['<index>'],
    ('<array_element>', '<'): ['<index>'],
    
    # PREDICT(<id_ext>) rules
    ('<id_ext>', '('): ['<func_call>'],
    ('<id_ext>', ','): ['<array_element>'],
    ('<id_ext>', '>'): ['<array_element>'],
    ('<id_ext>', '=='): ['<array_element>'],
    ('<id_ext>', '+='): ['<array_element>'],
    ('<id_ext>', '~'): ['<array_element>'],
    ('<id_ext>', '||'): ['<array_element>'],
    ('<id_ext>', '>='): ['<array_element>'],
    ('<id_ext>', ')'): ['<array_element>'],
    ('<id_ext>', '!='): ['<array_element>'],
    ('<id_ext>', '<='): ['<array_element>'],
    ('<id_ext>', '['): ['<array_element>'],
    ('<id_ext>', '%='): ['<array_element>'],
    ('<id_ext>', '/='): ['<array_element>'],
    ('<id_ext>', '+'): ['<array_element>'],
    ('<id_ext>', '-'): ['<array_element>'],
    ('<id_ext>', '/'): ['<array_element>'],
    ('<id_ext>', '*'): ['<array_element>'],
    ('<id_ext>', '&&'): ['<array_element>'],
    ('<id_ext>', '%'): ['<array_element>'],
    ('<id_ext>', '-='): ['<array_element>'],
    ('<id_ext>', '*='): ['<array_element>'],
    ('<id_ext>', '<'): ['<array_element>'],
    ('<id_ext>', ','): ['ε'],
    ('<id_ext>', '>'): ['ε'],
    ('<id_ext>', '=='): ['ε'],
    ('<id_ext>', '+='): ['ε'],
    ('<id_ext>', '~'): ['ε'],
    ('<id_ext>', '||'): ['ε'],
    ('<id_ext>', '>='): ['ε'],
    ('<id_ext>', ')'): ['ε'],
    ('<id_ext>', '!='): ['ε'],
    ('<id_ext>', '<='): ['ε'],
    ('<id_ext>', '%='): ['ε'],
    ('<id_ext>', '/='): ['ε'],
    ('<id_ext>', '+'): ['ε'],
    ('<id_ext>', '-'): ['ε'],
    ('<id_ext>', '/'): ['ε'],
    ('<id_ext>', '*'): ['ε'],
    ('<id_ext>', '&&'): ['ε'],
    ('<id_ext>', '%'): ['ε'],
    ('<id_ext>', '-='): ['ε'],
    ('<id_ext>', '*='): ['ε'],
    ('<id_ext>', '<'): ['ε'],
    
    # PREDICT(<array_size>) rules
    ('<array_size>', 'identifier'): ['identifier'],
    ('<array_size>', 'positive_treasures_lit'): ['positive_treasures_lit']
    } 

    def __init__(self, start_symbol):
        self.cfg = self.CFG
        self.predict = self.PREDICT
        self.start_symbol = start_symbol

    def parse(self, tokens):
        class DummyToken:
            token_type = 'EOF'
            value = 'EOF'
            line = -1
        tokens = list(tokens)
        tokens.append(DummyToken())
        pos = 0
        stack = ['EOF', self.start_symbol]
        step = 0
        while stack:
            step += 1
            if step > 10000:
                print("Infinite loop detected!")
                print("Stack:", stack)
                print("Current token:", current_token)
                break
            top = stack.pop()
            current_token = tokens[pos]
            current_token_type = current_token.token_type
            current_token_value = getattr(current_token, 'value', '')
            current_token_line = getattr(current_token, 'line', '?')

            if top == 'ε':
                continue
            elif top == current_token_type:
                pos += 1
            elif top in self.cfg:
                # Collect all possible lookaheads for this non-terminal
                expected = [lookahead for (nt, lookahead) in self.predict if nt == top]
                key = (top, current_token_type)
                if key in self.predict:
                    production = self.predict[key]
                    for symbol in reversed(production):
                        stack.append(symbol)
                else:
                    raise SyntaxError(
                        f"Syntax Error Unexpected input '{current_token_value}' at line {current_token_line}. "
                        f"Expected one of {expected}"
                    )
            else:
                raise SyntaxError(
                    f"Syntax Error Unexpected input '{current_token_value}' at line {current_token_line}. "
                    f"Expected one of ['{top}']"
                )
        if pos == len(tokens) - 1:
            print("Parsing succeeded!")
        else:
            # Unconsumed input
            current_token = tokens[pos]
            current_token_value = getattr(current_token, 'value', '')
            current_token_line = getattr(current_token, 'line', '?')
            raise SyntaxError(
                f"Syntax Error Unexpected input '{current_token_value}' at line {current_token_line}. "
                f"Expected end of input."
            )